LINUX = 'Linux'
WINDOWS = 'Windows'

SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600

PLAYER_WIDTH = 20
PLAYER_HEIGHT = 60

CURSOR_SIZE = 20

PLAYER_1 = 'PLAYER 1'
PLAYER_2 = 'PLAYER 2'

FONT_SIZE_32 = ("Press Start 2P", 32, "normal")
FONT_SIZE_26 = ("Press Start 2P", 26, "normal")

